### PR TITLE
Fixes several issues in main

### PR DESCRIPTION
**Pull request by Raghav323**
- [x] Fixed issues relating to linking of blob folder in python files 
- [x] Added Concept of Adaptive fps i.e. Improved fps while camera is still in Fusion files
- [x] Cleaned some unnecessary comments in python files

### CODE REVIEW

**Comment by shahpratham** [comment]
have all these code been tested on oakd-pro @Raghav323 ?

**Comment by shahpratham** [comment]
still do the testing once by tomorrow latest, so we can merge.

**Comment by shahpratham** [comment]
@Raghav323 fix the merge conflicts

**Comment by Raghav323** [comment]
I have tested all py files on Oak-D and they run properly and also retrieve the blob path correctly .

**Comment by Raghav323** [comment]
Many of the files are only showing the fusion frame and not the other frames . Should i change that ?

**Pull request merged**
